version: '3.8'

services:
  backend:
    image: inventory-backend-image
    build:
      context: /home/administrator/Documents/GitHub/inventory
      dockerfile: Dockerfile
    ports:
      - "3005:3006"
    volumes:
      - /home/administrator/Documents/GitHub/inventory:/usr/src/app:rw
      - /home/administrator/Documents/GitHub/storage/:/usr/src/app/storage:rw
    restart: always